version: '3.8'

services:
  db:
    image: postgres:13
    command: postgres -c max_connections=1000
    container_name: llm-api-db
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: example
    ports:
      - "5433:5433"