CREATE SCHEMA IF NOT EXISTS api;
SET SCHEMA 'api';

CREATE TABLE IF NOT EXISTS  users (
    id UUID PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompts (
    uuid UUID PRIMARY KEY,
    user_uuid UUID NOT NULL,
    content TEXT NOT NULL
);