version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - api-database
  #     - redis
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.117.139:5432/api?currentSchema=api
  #     SPRING_DATASOURCE_USERNAME: user
  #     SPRING_DATASOURCE_PASSWORD: password
  #     SPRING_REDIS_HOST: redis
  #     SPRING_REDIS_PORT: 6379
  #   ports:
  #     - "8080:8080"
  api-database:
    image: postgis/postgis:12-3.4
    command: postgres -c max_connections=1000
    container_name: api-db
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: user 
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    command:
        ["-path", "/src/main/resources/db/migrations", "-database", "postgresql://user:password@api-db:5432/api?sslmode=disable", "up"]
    volumes:
        - ./src/main/resources/db/migrations:/src/main/resources/db/migrations
    restart: on-failure:9 # will start 1 time and retry 9 times

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"